# Site settings
title:       Poems && Programs
email:       eric.q.weinstein@gmail.com
author:      Eric Weinstein
description: "Poems and programs by Eric Weinstein."
baseurl:     ""
url:         "http://ericweinste.in"

# Google analytics
google_analytics: "UA-9674815-3"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Brave
include: [".well-known"]

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username:   ericqweinstein
stackoverflow_id:
twitter_username:  ericqweinstein
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text:         'Share this post!'
# Change to 'true' to enable individual icons
share_facebook:     true
share_twitter:      true
share_googleplus:   true
share_linkedin:     true
share_digg:         false
share_tumblr:       false
share_reddit:       false
share_stumbleupon:  false
share_hackernews:   false

# Build settings
gems: ['jekyll-paginate']
markdown:     kramdown
kramdown:
  input:      GFM
permalink:    pretty
paginate:     3
sass:
  compressed: true
